import {reportShell} from './report-shell.mjs';
export function genericReport(data,evaluation){
const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const controlled=data.controlled!==false;
const names={pass:'符合预期',issue:'发现问题',blocked:'依赖受阻',unverified:'未完成验证'};const labels=evaluation.labels||{};
const actual=x=>{if(x?.books)return x.books.map(b=>`${b.title}：${b.read?'已读':'未读'}`).join('；');if(x?.totalCents!==undefined)return `批次 ${x.reference}，${x.count} 笔，${(x.totalCents/100).toFixed(2)} 元`;return typeof x==='string'?x:JSON.stringify(x)};
function budgetNote(b){return b?.currency?`<p class="note"><b>费用记录</b>：本轮上限 ${e(b.currency)} ${(b.limitMinor/100).toFixed(2)}；已预留费用上界 ${(b.heldMinor/100).toFixed(2)}。金额来自本次约定，非实际扣费；产品已有费用信息按页面证据核对，无需账单接入。结果未知的任务仍保留额度。</p>`:'';}
function discrepancy(g){const record=g.records.find(r=>r.checks?.some(k=>!k.setup&&k.pass===false&&k.status!=='unverified'));const check=record?.checks.find(k=>!k.setup&&k.pass===false&&k.status!=='unverified');return check?`<div class="discrepancy"><p><b>预期</b>　${e(actual(check.expected))}</p><p><b>实际</b>　${e(actual(check.actual))}</p><p class="note">${e(check.label)} · 第 ${record.attempt} 次；下方可打开操作记录、现场及实际产物。</p></div>`:'';}
function actualTrigger(g){const r=g.records.find(r=>r.status==='issue');if(!r)return g.path.trigger;const actions=r.actions.filter(a=>!a.setup&&!['goto','wait'].includes(a.type));const fills=actions.filter(a=>a.type==='fill').map(a=>a.label);const last=actions.filter(a=>a.type!=='fill').at(-1);if(r.reason==='任务明确失败，未取得预期结果')return (fills.length?'填写'+fills.join('、')+'，':'')+(last?'点击「'+last.label+'」。':'执行提交。');return g.path.trigger;}
function historyDetail(c,g){const h=c.result.history;if(!h)return '';const items=h.applied.filter(x=>x.pathId===g.path.id);return items.length?`<details class="history"><summary>查看本路径采用的历史条件</summary>${items.map(x=>`<section><p><b>历史明确要求</b>：${e(x.requirement)}</p><blockquote>${e(x.source.quote)}</blockquote><p class="note">原文：${e(x.source.file)}:${x.source.startLine} · 快照 SHA-256：${e(x.source.excerptHash)}</p><p><b>本次检查条件</b>：${e(x.condition)}</p><p>对应检查：${e(x.check)}；对应理由：${e(x.rationale)}</p><p class="note">第 ${x.revision} 版 · 操作者 ${e(x.actor)} · ${e(x.scope.project)} / ${e(x.scope.feature)}。条件到检查由助手或操作者对应，尚非自动语义判断。</p></section>`).join('')}</details>`:'';}
function detail(c,g){const impact=(data.impacts||[]).find(x=>x.pathId===g.path.id);return `<details><summary>查看依据、证据与重复验证</summary>${impact?`<p><b>${e(impact.label)}</b>：${e(impact.reason)}</p><p class="note">分级依据：${e(impact.goalBasis)} · ${e(impact.scope)}${impact.alternativePaths.length?"；已验证替代路径："+e(impact.alternativePaths.join("、")):""}</p>`:""}<p class="note">依据：${g.path.basis.map(e).join('、')} · ${e(c.result.planSource)}</p>${g.evidence?`<p data-evidence="${e(g.evidence.state)}">${e(g.evidence.label)}：正常 ${g.evidence.counts.pass} 次，异常 ${g.evidence.counts.issue} 次，未验证 ${g.evidence.counts.unverified} 次${g.evidence.interrupted?'；复验因受阻或未知状态中断':''}。</p>`:''}${historyDetail(c,g)}${g.records.map(r=>`<section class="attempt"><h4>第 ${r.attempt} 次 · ${e(names[r.status])}</h4><p>${e(r.reason)}${r.permissionStop?'；已保留现有证据，未授权部分不计通过':''}${r.recoveries?.length?'；控件重新观察 '+r.recoveries.length+' 次':''} · ${(r.elapsedMs/1000).toFixed(2)} 秒</p>${r.snapshotProtection?.some(s=>s.status==='omitted')?'<p>部分截图保护未完成，未保留图片；见操作记录。</p>':''}${r.checks.filter(k=>!k.setup).map(k=>`<p>${e(k.label)}${k.status==='unverified'?' · 未完成验证':''}<br>预期：${e(actual(k.expected))}<br>实际：${e(actual(k.actual))}</p>`).join('')}<div class="links"><a href="${c.id}/${r.id}.json" target="_blank">操作记录</a>${r.snapshots.filter(s=>s.phase===g.path.id+'-result'||s.phase.includes('failure')).map(s=>`<a href="${c.id}/${s.file}" target="_blank">结果现场</a>`).join('')}${r.outputs.map(f=>`<a href="${c.id}/${f}" target="_blank">${r.outputProtection?.find(x=>x.file===f)?.redacted?'脱敏后的导出副本':'实际导出文件'}</a>`).join('')}</div></section>`).join('')}</details>`}
const issues=data.cases.flatMap(c=>c.result.groups.filter(g=>g.status==='issue'||g.findings?.length).map(g=>`<article id="issue-${e(g.path.id)}" data-status="issue"><div class="rowhead"><span class="tag issue">${e(g.evidence?.label||'发现问题')}</span><span class="muted">${e(c.result.project)}${labels[c.id]?' · '+e(labels[c.id]):''}</span></div><h3>问题：${e(g.reason)}</h3><p><b>位置</b>　${e(g.path.location)}</p><p><b>操作</b>　${e(actualTrigger(g))}</p><details><summary>查看预期与实际差异</summary>${discrepancy(g)}${g.findings?.length?`<ul class="findings">${g.findings.map(f=>`<li>${e(f.check||f.reason)}：${e(f.reason)}（第 ${f.attempts.map(e).join('、')} 次）</li>`).join('')}</ul>`:''}</details>${detail(c,g)}</article>`)).join('');
const coverage=data.cases.map(c=>{const counts=Object.fromEntries(['pass','issue','blocked','unverified'].map(s=>[s,c.result.groups.filter(g=>g.status===s).length]));return `<details class="coverage"><summary><span>${e(c.result.project)}${labels[c.id]?' / '+e(labels[c.id]):''}</span><span class="muted">${counts.pass} 符合预期 · ${counts.issue} 问题${counts.blocked?' · '+counts.blocked+' 受阻':''}${counts.unverified?' · '+counts.unverified+' 未验证':''}</span></summary><p class="note">目标：${e(c.result.goal)}</p>${budgetNote(c.result.budget)}${c.result.groups.map(g=>`<section class="pathrow" data-status="${g.status}"><p><span class="tag ${g.status==='blocked'?'unverified':g.status}">${e(names[g.status])}</span> <b>${e(g.path.name)}</b> <span class="muted">${g.records.length} 次</span></p><p class="note">${e(g.reason)}</p>${g.status==='issue'?'':detail(c,g)}</section>`).join('')}</details>`}).join('');
return reportShell({data,evaluation,controlled,issues,coverage,e});
}
