import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {compileTask} from './planner.mjs';
import {applyAnalysis,validateAnalysis,experienceOutcomes,createAutoExperienceStore,summarizeExperienceImpact} from './auto-experience.mjs';
import {readReportFile} from '../lib/report-file.mjs';
import {workbenchJS} from './workbench-page.mjs';
const input=()=>({url:'http://127.0.0.1:4567/',materials:[{id:'source',hash:'hash',label:'纠正.md',kind:'project-material',content:'报告详情正文默认收起，需要时再展开。'}],observedTargets:[{id:'detail',target:{css:'#detail'}}]});
const value=()=>({items:[{sourceId:'source',quote:'报告详情正文默认收起，需要时再展开。',kind:'requirement',summary:'默认收起详情',scope:'报告首次打开',decision:'apply',reason:'当前报告任务适用',handoff:'将详情正文放进默认收起的区域',question:'',checks:[{targetId:'detail',type:'visible',expectedText:'',expectedBoolean:false,expectedCount:0,label:'详情默认隐藏'}]}],noExperienceReason:''});
const task=()=>compileTask({id:'task-test',goal:'检查报告页面',normalRuns:2,intake:{root:'/fixture',fingerprint:'version',fingerprintScope:'scanned-files-only',requirements:[],files:[],gaps:[]},observation:{url:input().url,title:'报告',headings:[],fields:[],buttons:[],blocked:[],readRules:[]}});
test('经验真正增加只读断言，原计划及授权不被覆盖',()=>{const t=task(),next=applyAnalysis(t,value(),input(),{provider:'test-double'});assert.equal(t.plan.paths.length,1);assert.equal(next.plan.paths.length,2);assert.deepEqual(next.proposedScope,t.proposedScope);assert.deepEqual(next.plan.paths.at(-1).checks.map(c=>[c.type,c.expected]),[['count',1],['visible',false]]);assert.equal(next.autoExperience.decisions[0].source.quote,value().items[0].quote);});
test('引用、未知控件、偏好、停用、额外动作和逐项确认有程序边界',()=>{for(const mutate of [v=>v.items[0].quote='杜撰的一段原话',v=>v.items[0].checks[0].targetId='unknown',v=>v.items[0].kind='preference',v=>v.items[0].kind='uncertain',v=>v.items[0].decision='suggest',v=>v.items[0].checks[0].command='send',v=>v.items[0].question='请确认采用吗？']){const v=value();mutate(v);assert.throws(()=>validateAnalysis(v,input()));}const i=input();i.materials[0].disabled=true;assert.throws(()=>validateAnalysis(value(),i));});
test('应用、执行符合、失败、未执行和移除分别记录，缺记录不算通过',()=>{const t=applyAnalysis(task(),value(),input(),{}),id=t.autoExperience.decisions[0].mappedPaths[0],out=r=>experienceOutcomes(t,r).decisions[0];assert.equal(out(null).outcome,'not-run');assert.equal(out({groups:[]}).outcome,'unverified');assert.equal(out({groups:[{path:{id},status:'pass',records:[]}]}).outcome,'unverified');for(const status of ['pass','issue'])assert.equal(out({groups:[{path:{id},status,records:[{id:'run',status,snapshots:[]}]}]}).outcome,status==='pass'?'requirement-met':'requirement-not-met');t.excludedPaths.push(id);assert.equal(out(null).outcome,'outside-scope');assert.match(out(null).benefit,/不代表/);});
test('同项目反馈自动读取、原文件重新核对、停用与结果回流，其他项目隔离',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'auto-store-test-'));try{const root=path.join(dir,'project');await fs.mkdir(root);await fs.writeFile(path.join(root,'纠正.md'),'报告详情正文默认收起，需要时再展开。');const store=await createAutoExperienceStore(path.join(dir,'state'));const first=await store.collect(root,['纠正.md']);await store.feedback(root,{task:{id:'task-test',revision:1,goal:'报告页面'},text:'这次详情改为默认展开，便于审核全文。'});await store.disable(root,first.materials[0].id);const second=await store.collect(root,[]);assert.equal(second.materials.length,2);assert.ok(second.materials[0].disabled);assert.equal((await store.collect('/different-project',[])).materials.length,0);const t=applyAnalysis(task(),value(),input(),{});await store.outcome(root,t,{groups:[]});assert.equal((await store.collect(root,[])).priorOutcomes[0].decisions[0].outcome,'unverified');await fs.writeFile(path.join(root,'纠正.md'),'报告详细内容本次全部展开。');assert.notEqual((await store.collect(root,[])).materials[0].hash,first.materials[0].hash);await fs.unlink(path.join(root,'纠正.md'));assert.equal((await store.collect(root,[])).gaps.length,1);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('资料读取拒绝越界、符号链接及超限文件',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'auto-read-test-'));try{await fs.writeFile(path.join(dir,'a.md'),'12345');await fs.symlink(path.join(dir,'a.md'),path.join(dir,'b.md'));await assert.rejects(readReportFile(dir,'a.md',{maxBytes:4}));await assert.rejects(readReportFile(dir,'../a.md'));await assert.rejects(readReportFile(dir,'b.md'));}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('浏览器脚本可解析',()=>assert.doesNotThrow(()=>new Function(workbenchJS)));

test('旧任务一次性例外不会因模型采用而进入新任务执行',()=>{const v=value(),i=input();v.items[0].kind='exception';i.materials[0].taskId='past-task';const t=applyAnalysis(task(),v,i,{});assert.equal(t.plan.paths.length,1);assert.equal(t.autoExperience.decisions[0].decision,'skip');assert.equal(t.autoExperience.decisions[0].policyOverride,'past-task-exception');});

test('跨任务纵向记录区分实际结果与尚未测得的人类收益',()=>{const source={id:'source',label:'纠正.md'},decision=(outcome,executedPaths=1)=>({source,decision:'apply',outcome,executedPaths});const impact=summarizeExperienceImpact([
 {kind:'outcome',taskId:'t1',at:'2026-09-16T01:00:00Z',outcomes:{decisions:[decision('requirement-not-met')]}},
 {kind:'outcome',taskId:'t2',at:'2026-09-16T02:00:00Z',outcomes:{decisions:[decision('requirement-met')]}},
 {kind:'disabled',sourceId:'other'}
 ]);assert.equal(impact.tasks,2);assert.equal(impact.sources[0].tasks,2);assert.equal(impact.sources[0].outcomes['requirement-met'],1);assert.equal(impact.sources[0].status,'needs-repair');assert.equal(impact.humanBenefit.status,'unmeasured');assert.equal(impact.humanBenefit.userActiveMs,null);});
