import test from 'node:test';
import assert from 'node:assert/strict';
import {businessAdvice,businessAdviceHTML} from './business-advice.mjs';
import {codexContext} from './codex-context.mjs';
const fixture=()=>({task:{id:'task-advice',mode:'reviewed-reading',goal:'导出',revision:1,digest:'v1',plan:{paths:[{id:'export'}]}},evidenceVerified:true,result:{groups:[{path:{id:'export',name:'导出',location:'清单',trigger:'下载',basis:['README.md:11']},status:'issue',records:[0,1].map(i=>({id:'export-'+i,status:'issue',outputs:['export-'+i+'.json'],checks:[{status:'issue',expected:{read:true},actual:{read:false},label:'状态'}]}))}]}});
test('export advice links repeated output differences without asserting a root cause or benefit',()=>{const a=businessAdvice(fixture())[0];assert.equal(a.kind,'product-mismatch');assert.equal(a.facts[0].records.length,2);assert.match(a.unknown,/尚未证明具体根因/);assert.match(a.next,/核对/);assert.match(a.recheck,/至少两次/);assert.equal(a.userTimeSavedMs,null);});
test('missing seal, output, repetition or executor completion becomes evidence gap',()=>{for(const mutate of [x=>x.evidenceVerified=false,x=>x.result.groups[0].records.pop(),x=>x.result.groups[0].records[0].outputs=[],x=>x.result.groups[0].status='unverified']){const f=fixture();mutate(f);const a=businessAdvice(f)[0];assert.equal(a.kind,'evidence-gap');assert.equal(a.facts.length,0);assert.match(a.next,/不先判定业务根因/);}});
test('feedback changes the suggested next step, never its measured effect or execution result',()=>{for(const decision of ['accept','reject','correct']){const f=fixture(),id=businessAdvice(f)[0].id;f.opinions=[{adviceId:id,adviceDecision:decision,text:'<script>override</script>'}];const a=businessAdvice(f)[0];assert.equal(a.decision,decision);assert.equal(a.effectStatus,'unmeasured');assert.equal(f.result.groups[0].status,'issue');if(decision==='reject')assert.match(a.next,/已拒绝/);assert.ok(!businessAdviceHTML([a]).includes('<script>'));const text=codexContext({task:f.task,root:'/fixture',businessAdvice:[a]}).text;assert.match(text,/不授予执行权限/);assert.match(text,/"effectStatus":"unmeasured"/);}});
test('resolved, unrelated and inactive paths do not create current export advice',()=>{for(const mutate of [f=>f.task.mode='basic',f=>f.result.groups[0].status='pass',f=>f.task.plan.paths=[]]){const f=fixture();mutate(f);assert.deepEqual(businessAdvice(f),[]);}});
