import {ownProjectGuide} from './connect-page.mjs';
export function cloudPage(token){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>验收助手</title><link rel="stylesheet" href="/cloud.css"></head><body><main><div class="mark"></div><h1>说说你想完成什么。</h1><section id="answer" aria-live="polite" hidden></section><form id="chat"><label for="goal" class="sr">你的目标</label><textarea id="goal" required maxlength="2000" placeholder="写下目标，或输入“查看案例”。"></textarea><div class="bottom"><span>写目标 → 检查 → 修复复检 <button id="help" type="button" class="text">怎么开始</button></span><button id="send" aria-label="发送">↑</button></div></form><p id="status" role="status"></p><nav><button id="own-project" type="button" class="text">检查我的产品</button><a href="/guide-video">看 3 分半视频</a><a href="https://github.com/jilombmiker-alt/acceptance-assistant" target="_blank" rel="noopener">项目代码</a></nav><p class="note">在线体验使用内置案例，实际运行检查。自己的代码请点“检查我的产品”，按指引在本机接入。</p></main><script src="/cloud.js" data-task-token="${token}"></script></body></html>`;}
export const cloudCSS=`*{box-sizing:border-box}body{margin:0;background:#fff;color:#111;font:16px/1.75 system-ui,-apple-system,"PingFang SC",sans-serif}main{max-width:744px;margin:auto;padding:18vh 28px 48px}.mark{width:32px;height:6px;background:#111;margin-bottom:24px}h1{font-size:30px;line-height:1.4;margin:0 0 32px}form{border:2px solid;padding:20px 22px}textarea{width:100%;min-height:110px;resize:vertical;border:0;outline:none;font:17px/1.75 inherit;color:#111;background:white}.bottom{display:flex;align-items:center;justify-content:space-between;gap:12px}.bottom span,.note,nav,#status{font-size:12px;color:#666}button{font:inherit;border:2px solid #111;background:#111;color:white;min-height:44px;padding:8px 14px;cursor:pointer}button:disabled{opacity:.45;cursor:wait}#send{font-size:25px;width:46px;line-height:1}.text{border:0;padding:0 4px;background:white;color:#111;font-size:12px;text-decoration:underline;text-underline-offset:4px}a{color:#111;text-underline-offset:4px}nav{display:flex;gap:22px;margin-top:20px}.note{margin-top:20px}#answer{margin:0 0 26px;overflow-wrap:anywhere}#answer button{margin:6px 8px 6px 0;font-size:14px}#answer a{display:inline-block;margin:6px 18px 6px 0}#answer p{margin:0 0 12px}details{margin:14px 0}summary{cursor:pointer}li{font-size:14px}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}[hidden]{display:none!important}:focus-visible{outline:3px solid #111;outline-offset:4px}@media(max-width:600px){main{padding:80px 22px 32px}h1{font-size:25px}.bottom span{font-size:11px}form{padding:18px}}`;
export const cloudJS=String.raw`
const token=document.currentScript.dataset.taskToken,el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state,busy=false,timer;
function answer(html){el('answer').hidden=false;el('answer').innerHTML=html;}
function lock(v){busy=v;el('send').disabled=v;el('help').disabled=v;el('answer').querySelectorAll('button').forEach(b=>b.disabled=v);}
async function read(route){const r=await fetch(route);const d=await r.json();if(!r.ok)throw Error(d.error||'暂时无法完成，请重试');return d;}
async function post(route,data){const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json','X-Task-Token':token},body:JSON.stringify({...data,...(route==='/prepare'?{}:{taskId:state.task.id,revision:state.task.revision})})});const d=await r.json();if(!r.ok)throw Error(d.error||'暂时无法完成，请重试');state=d;return d;}
const ownProjectGuide=${JSON.stringify(ownProjectGuide)};
function choices(){answer('<p>线上可实际检查阅读清单：新增、状态变更、筛选、刷新保留和导出。选择一个版本，再查看计划并开始。</p>'+state.examples.map((s,i)=>'<button type="button" data-case="'+i+'">'+esc(s.label)+'</button>').join('')+'<p>每项重复 2 次，按最终结果判断；故障样例用于验证能否发现问题。</p>');}
function plan(){answer('<p>已准备好 '+state.task.checks.length+' 项检查。点击开始后，服务器会实际打开样例并运行。</p><details><summary>查看本次检查范围</summary><ul>'+state.task.checks.map(c=>'<li>'+esc(c.module)+'：'+esc(c.expected)+'</li>').join('')+'</ul></details><button id="run" type="button">开始检查</button>');}
async function poll(){try{state=await read('/state');if(state.control?.reportAvailable){clearTimeout(timer);const r=await read('/results.json'),groups=r.execution?.groups||[],issues=groups.filter(g=>g.status==='issue'),blocked=groups.filter(g=>g.status==='blocked');answer('<p>本轮检查完成：发现 '+issues.length+' 项问题'+(blocked.length?'，另有 '+blocked.length+' 条路径受阻':'')+'。</p>'+issues.map(g=>'<p>'+esc(g.path?.name||g.path?.id)+'：请查看预期与实际结果。</p>').join('')+'<a href="/report" target="_blank" rel="noopener">查看报告与证据</a><button id="again" type="button">换正常版本复检</button><p>这里只证明已覆盖的案例结果，未测得人工时间或经济损耗节省。</p>');el('status').textContent='';lock(false);return;}if(state.control?.errorMessage)throw Error(state.control.errorMessage);timer=setTimeout(poll,1200);}catch(e){el('status').textContent=e.message;lock(false);}}
async function comparison(){const d=await read('/repair-case.json');answer('<p>'+esc(d.flow)+'</p><p>修复前 '+d.before.issues+' 项偏差 → 修复后 '+d.after.issues+' 项；相同 '+d.criteria.length+' 项标准，各重复 '+d.repetitions+' 次。</p><p>该对比来自已完成的独立受控实测。人工时间节省尚未测得。</p><a href="/repair-case.json" target="_blank">查看完整对比记录</a><button id="try" type="button">我也运行一次验收</button>');}
el('answer').onclick=async e=>{const b=e.target.closest('button');if(!b||busy)return;try{lock(true);if(b.dataset.case!==undefined){await post('/prepare',{...state.examples[Number(b.dataset.case)],normalRuns:2});plan();}else if(b.id==='run'){await post('/start',{confirmed:true,digest:state.task.digest});answer('<p>正在实际检查，完成后告诉你先改哪里。</p><a href="/workbench" target="_blank" rel="noopener">查看进度或暂停</a>');el('status').textContent='检查通常需要几十秒，请保留当前页面。';poll();return;}else if(b.id==='again'){await post('/prepare',{...state.examples[0],normalRuns:2});plan();}else choices();}catch(e){el('status').textContent=e.message;}finally{if(!state.control?.worker?.running)lock(false);}};
el('own-project').onclick=()=>{if(!busy)answer(ownProjectGuide);};
el('help').onclick=()=>{el('goal').value='怎么开始';el('chat').requestSubmit();};
el('chat').onsubmit=async e=>{e.preventDefault();if(busy)return;const text=el('goal').value.trim();el('goal').value='';el('status').textContent='';lock(true);try{if(/上传|代码|我的产品|自己的|接入|本地|怎么用|怎么开始/.test(text))answer(ownProjectGuide);else if(/视频/.test(text))answer('<p>观看从目标、检查到修复复检的完整讲解。</p><a href="/guide-video">播放 3 分 30 秒视频</a>');else if(/案例|对比|效果/.test(text))await comparison();else if(/怎么|帮助|指南/.test(text))answer('<p>写下你想检查的目标，选择内置版本，再点“开始检查”。报告会说明问题、位置、触发操作，并提供可查看的证据。</p><p>想了解个人经验如何改变检查，输入“查看案例”。</p><button id="try" type="button">开始体验</button>');else choices();}catch(e){el('status').textContent=e.message;}finally{lock(false);}};
lock(true);read('/state').then(s=>{state=s;lock(false);if(s.control?.worker?.running){answer('<p>正在恢复本轮检查进度…</p>');lock(true);poll();}else if(s.task&&!s.receipt)plan();}).catch(e=>{el('status').textContent=e.message;});
`;
export const videoPage=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>验收助手 · 使用视频</title><link rel="stylesheet" href="/cloud.css"><main style="max-width:1120px;padding-top:48px"><a href="/">回到对话</a><h1 style="margin-top:24px">从一句目标，到修复复检</h1><video controls preload="metadata" playsinline style="width:100%;border:2px solid #111" src="/guide.mp4"></video><p>3 分 30 秒 · 中文旁白与字幕 · 实际界面截图讲解与独立受控修复对比。</p><a href="/guide.mp4">直接打开视频</a></main></html>`;
