export function lightPage(html){
 const start=html.match(/<button id="start">[\s\S]*?<\/button>/)?.[0];
 const goal=html.match(/<label for="goal">[\s\S]*?<\/textarea>/)?.[0];
 const submit=html.match(/<button type="submit">读取资料并生成检查计划<\/button>/)?.[0];
 if(!start||!goal||!submit)throw Error('轻入口缺少原验收控件');
 let next=html.replace('<body>','<body id="top" data-light>');
 next=next.replace(/<header>[\s\S]*?<\/header>/,'<div class="product-bar"><a class="product-brand" href="#top">验收助手</a><nav aria-label="主要导航"><a href="#case-demo">修复案例</a><a href="#codex-guide">带回 Codex</a><a href="#user-guide">使用指南</a></nav><span class="local-indicator">本地运行</span></div><header class="light-header"><h1>说清目标，接着往下做。</h1><p>结合本项目的历史，检查问题、整理改进，再核对实际结果。</p></header>');
 // Move, do not duplicate, the existing form inputs and authorized start action.
 next=next.replace(goal,'').replace(submit,'').replace(start,'');
 next=next.replace('<section id="intake"><h2>1. 选择项目与目标</h2>','<section id="intake"><h2 class="visually-hidden">这次想完成什么</h2>');
 next=next.replace('<form id="prepare">','<form id="prepare"><div class="goal-composer">'+goal.replace('这次希望检查什么','这次想完成什么').replace('例如：检查页面入口、表单填写和手机宽度下的可用性','例如：帮我检查这次报告改动，沿用之前的呈现要求，找出还需要修复的问题。')+'<div class="composer-bottom"><span id="active-project">读取项目…</span><button type="submit">生成下一步</button></div><button type="button" id="light-feedback" class="text-button">这是一条对本轮的纠正</button></div><details id="project-settings"><summary>项目、历史资料与检查设置</summary>');
 // The first closing form belongs to the intake form.
 next=next.replace('</form></section>','</details></form></section>');
 const userGuide=next.match(/<details id="user-guide">[\s\S]*?<\/details>/)?.[0]||'';
 next=next.replace(userGuide,'');
 const reply='<div id="light-reply" hidden aria-live="polite"><p id="light-user-goal" class="user-message"></p><div class="assistant-message"><h2 id="light-reply-title">下一步</h2><p id="light-reply-text"></p><ul id="light-reminders"></ul><div class="light-actions">'+start+'<a href="/codex-context.md" id="codex-context-link" download>带着经验去 Codex 继续</a><a href="/report" id="light-report-link">查看本轮证据</a></div><details id="codex-guide"><summary>怎样接入 Codex 和日常使用？</summary><p>下载本次项目上下文，作为 Codex 下一条任务的附件或粘贴内容。里面保留适用条件、检查要求、原执行状态和下一步。</p><p>项目内资料和反馈会在本助手的下一任务中重新判断；跨项目默认不套用。长期项目约定可整理进项目 AGENTS.md，可复用流程可做成 Skill。本次提供上下文导出，尚未自动安装，也未自动采集你的其他聊天。</p><p><a href="https://learn.chatgpt.com/docs/agent-configuration/agents-md" target="_blank" rel="noreferrer">Codex 官方项目指引</a></p></details><a href="#full-workbench" id="open-full-workbench">展开完整计划、控制与审评指标</a></div></div>';
 const caseDemo='<details id="case-demo"><summary>看一个案例：从发现问题到修复复检</summary><div id="repair-case"><p>正在读取已完成的修复案例。该案例独立于当前任务。</p></div><details><summary>本工具能做什么、效果怎样验证？</summary><p>支持本地页面入口、明确文字、输入回读、窄屏溢出、原生详情展开，以及项目内 JSON 记录打开与下载核对。相关历史可以增加有来源的检查；未覆盖目标会保留缺项。</p><p>先判断最终结果，再比较重复解释、返工、绕行、盯守及时间成本。单次修复、更多检查和更少点击，都不能直接证明个人历史节省了真人时间。</p></details></details>';
 next=next.replace('<section id="task"',reply+caseDemo+'<details id="full-workbench"><summary>完整验收工作台</summary><section id="task"');
 next=next.replace('<footer>','</details>'+userGuide+'<footer>');
 // Keep integration help accessible even before the first task exists.
 const codexGuide=next.match(/<details id="codex-guide">[\s\S]*?<\/details>/)?.[0]||'';
 next=next.replace(codexGuide,'').replace('<details id="case-demo">',codexGuide+'<details id="case-demo">');
 return next;
}

export function renderRepairCase(data){
 const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(!data)return '<p>案例尚未载入；可以先查看本轮执行证据。</p>';
 return '<p class="case-kind">受控修复实测 · 独立案例，不是当前任务的修复结果</p><h3>'+e(data.title)+'</h3><p>'+e(data.flow)+'</p><div class="repair-comparison"><div><h4>修复前</h4><p>'+e(data.before.description)+'</p><strong>'+data.before.issues+' 项偏差</strong></div><div><h4>修复后</h4><p>'+e(data.after.description)+'</p><strong>'+data.after.issues+' 项偏差</strong></div></div><p>实际修改：'+e(data.change)+'</p><p>固定 '+data.criteria.length+' 项验收，每个版本重复 '+data.repetitions+' 次；'+e(data.result)+'</p><p>检查耗时：修复前 '+(data.before.elapsedMs/1000).toFixed(2)+' 秒，修复后 '+(data.after.elapsedMs/1000).toFixed(2)+' 秒。它是本次测试耗时，不能折算为用户节省。</p><p class="case-kind">真人操作时间、返工时间、经济损耗：未测得。收益判断仍需公平对照。</p><a href="/repair-case.json" download>下载前后版本、验收项与原始结果索引</a>';
}

export const lightCSS=`
body[data-light] main{max-width:980px;padding:0 36px 32px}body[data-light] .product-bar{min-height:74px}body[data-light] header.light-header{padding:42px 0 24px;border:0}body[data-light] .light-header h1{font-size:34px;line-height:1.4;margin:0 0 12px;letter-spacing:-.025em}body[data-light] .light-header p{color:#4e6072;font-size:16px;margin:0}.visually-hidden{position:absolute!important;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
body[data-light] #intake{margin:0;padding:0;border:0;background:none;max-width:none}body[data-light] #reuse-project{display:none}body[data-light] #prepare{display:block}body[data-light] .goal-composer{background:white;border:1px solid #aabaca;border-radius:12px;padding:18px 20px}body[data-light] .goal-composer label{margin:0;font-size:13px;color:#4e6072}body[data-light] .goal-composer textarea{border:0;padding:12px 0;min-height:116px;resize:vertical;font-size:17px;line-height:1.7;outline-offset:0}body[data-light] .composer-bottom{display:flex;align-items:center;justify-content:space-between;gap:18px;border-top:1px solid #e1e7ef;padding-top:14px}.composer-bottom span{font-size:12px;color:#4e6072;overflow-wrap:anywhere}body[data-light] .composer-bottom button{font-size:14px;min-width:124px}.text-button{border:0!important;background:none!important;color:#4e6072!important;font-size:12px!important;padding:8px 0!important;min-height:36px!important;font-weight:400!important;text-decoration:underline;text-underline-offset:4px}body[data-light] #project-settings{margin:4px 0 0;padding-bottom:12px}body[data-light] #project-settings>summary{font-size:13px;color:#4e6072;font-weight:400}body[data-light] #project-settings[open]{padding-bottom:24px}body[data-light] #message{margin:12px 0;font-size:14px}body[data-light] #light-reply{padding:12px 0 24px}.user-message{font-size:14px;color:#4e6072;padding:12px 0;border-bottom:1px solid #cbd5df}.assistant-message h2{font-size:21px;margin:22px 0 12px}.assistant-message p,.assistant-message li{font-size:15px}.assistant-message ul{padding-left:20px}.light-actions{display:flex;align-items:center;flex-wrap:wrap;gap:12px 22px;margin:20px 0}.light-actions a{font-size:13px}body[data-light] #open-full-workbench{font-size:12px;font-weight:400}body[data-light] #codex-guide{margin:8px 0 18px;font-size:13px}body[data-light] #codex-guide summary{font-size:13px;color:#4e6072}body[data-light] #case-demo,body[data-light] #full-workbench{border-top:1px solid #cbd5df;padding:6px 0;margin-top:12px}body[data-light] #case-demo>summary{font-size:15px}body[data-light] #full-workbench>summary{font-size:13px;color:#4e6072}body[data-light] #full-workbench section{padding:24px;margin:14px 0}body[data-light] #case-demo h3{font-size:21px;margin:20px 0 10px}body[data-light] #case-demo p{font-size:14px}.case-kind{font-size:12px!important;color:#4e6072}.repair-comparison{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #cbd5df;border-bottom:1px solid #cbd5df;gap:24px;padding:16px 0}.repair-comparison h4{font-size:14px;margin:0 0 8px}.repair-comparison strong{font-size:17px}.repair-comparison div+div{border-left:1px solid #cbd5df;padding-left:24px}body[data-light] footer{font-size:12px}body[data-light] #user-guide{margin-top:12px}
@media(max-width:640px){body[data-light] main{padding:0 18px 24px}body[data-light] header.light-header{padding-top:28px}body[data-light] .light-header h1{font-size:27px}body[data-light] .light-header p{font-size:14px}body[data-light] .goal-composer{padding:16px}body[data-light] .goal-composer textarea{font-size:16px}body[data-light] .composer-bottom{align-items:flex-start;gap:12px}.composer-bottom span{max-width:55%}body[data-light] .composer-bottom button{min-width:104px;padding:9px 12px}.light-actions{align-items:start;gap:14px}.repair-comparison{gap:16px}.repair-comparison div+div{padding-left:16px}}
`;
