import test from 'node:test';import assert from 'node:assert/strict';
import {compileTask} from './planner.mjs';import {compileReportJourneys,reportImpact} from './report-journeys.mjs';
const make=()=>{const observation={url:'http://127.0.0.1:4567/',title:'报告',fields:[],blocked:[],readRules:[],reportJourneys:[{id:'expand-one',kind:'expand',name:'展开详情',dimension:'交互反馈',steps:[{type:'goto',path:'http://127.0.0.1:4567/'},{type:'click',target:{css:'summary'}}],checks:[{type:'visible',target:{css:'#detail'},expected:true,label:'正文可见'}]}]};return {observation,task:compileTask({id:'task',goal:'展开报告并查看证据',normalRuns:2,intake:{files:[],requirements:[],gaps:[],fingerprint:'v'},observation})};};
test('通用检查编译实际点击次数，缩小范围不重新纳入路径',()=>{const {task,observation}=make();const t=compileReportJourneys(task,observation);assert.equal(t.proposedScope.actions[0].maxInvocations,2);assert.equal(t.plan.paths.length,2);const x=compileReportJourneys(task,observation,{excludedPaths:['report-expand-one']});assert.equal(x.plan.paths.length,1);assert.equal(x.checks.at(-1).status,'outside-scope');});
const group=(id,status,hash='same')=>({path:{id,reportRole:'document',document:{valueHash:hash},steps:[{type:'goto'}]},status,records:[{},{}],evidence:{state:status==='issue'?'reproduced':'verified'}});
const impacts=groups=>reportImpact({goal:'查看证据',reportContract:{requestedResult:true},plan:{paths:groups.map(g=>g.path)}},{groups});
test('实际替代路径可用才分二级，全部结果路径重复失败才分一级',()=>{assert.equal(impacts([group('a','issue'),group('b','pass')])[0].level,2);assert.equal(impacts([group('a','issue'),group('b','issue')])[0].level,1);assert.equal(impacts([group('a','issue'),group('b','unverified')])[0].level,null);assert.equal(impacts([group('a','issue'),group('b','pass','different')])[0].level,1);});
test('展示偏差且结果已取得才分三级，疑似或缺证据保留未知',()=>{const p={...group('personal-view','issue'),path:{id:'personal-view',reportRole:'presentation',steps:[{type:'goto'}]}};assert.equal(impacts([p,group('result','pass')])[0].level,3);assert.equal(impacts([p])[0].level,null);const a=group('a','issue');a.evidence.state='suspected';assert.equal(impacts([a])[0].level,null);});

test('导出 PDF 的目标不能被 JSON 证据检查冒充完整终点',()=>{const {task,observation}=make();task.goal='只导出 PDF 报告';assert.equal(compileReportJourneys(task,observation).reportContract.requestedResult,false);});
