export const showcaseShell=`<div class="product-bar"><a class="product-brand" href="#top" aria-label="验收助手首页"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><rect x="3" y="3" width="26" height="26" rx="7" stroke="currentColor" stroke-width="2"/><path d="m9 16 5 5 10-11" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>验收助手</a><nav aria-label="主要导航"><a href="#stage">经验到行动</a><a href="#intake">发起验收</a><a href="#execution">本轮结果</a><a href="#user-guide">使用指南</a></nav><span class="local-indicator">本地运行</span></div><header id="stage" class="showcase"><div class="showcase-intro"><h1>让上一次纠正，<br>成为下一次的检查。</h1><p class="showcase-lead">把个人经验带进产品验收。自动判断适用性，执行具体检查，再用实际结果验证。</p><div class="showcase-actions"><a id="stage-primary" class="action-link" href="#intake">开始一次验收 <span aria-hidden="true">→</span></a><a href="#task">查看经验如何生效</a></div><p id="stage-status" class="showcase-status" role="status">正在读取本机任务…</p></div><div id="stage-case" class="showcase-case"><h2>从经验到结果</h2><p>读取已有任务后，在这里查看真实的来源、检查与证据。</p></div></header><div class="showcase-principle"><strong>判断适用 → 执行检查 → 核对结果 → 留下纠正</strong><span>执行变化可追溯，用户收益待对照。</span></div>`;

export function showcaseCase(state){
 const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const task=state.task,a=state.automatic,d=a?.decisions?.find(d=>d.mappedPaths?.length)||a?.decisions?.[0];
 if(!task)return '<h2>从一个真实目标开始</h2><p class="case-intro">选择下方受控样例，或接入自己的本地项目。</p><ol class="case-flow"><li><span>经验</span><p>提供之前的一条具体纠正</p></li><li><span>判断</span><p>系统判断是否适用于本次目标</p></li><li><span>验证</span><p>执行后查看结果与原始证据</p></li></ol><p class="case-note">未接入历史时，仍可进行通用检查。</p>';
 const measured=state.helpEvaluation?.observations,ready=state.control?.reportAvailable;
 const issues=state.impacts||[];
 const quote=d?.quote||'本轮没有采用个人历史，使用当前目标与通用检查。';
 const change=d?.mappedPaths?.map(id=>task.plan.paths.find(p=>p.id===id)?.name).filter(Boolean)||[];
 const outcome=!ready?'等待执行，结果尚未取得':issues.length?'发现 '+issues.length+' 项偏差，已保留操作与复现证据':'已覆盖路径未确认偏差，未验证范围仍需检查';
 return '<div class="case-heading"><h2>'+e(task.plan.project||'本次验收')+'</h2><span class="case-state">'+(ready?'已有执行记录':'计划待执行')+'</span></div><p class="case-intro">'+e(task.goal)+'</p><ol class="case-flow"><li><span>历史依据</span><blockquote>'+e(quote)+'</blockquote>'+(d?'<small>来源：'+e(d.source.label)+'</small>':'')+'</li><li><span>本次行动</span><p>'+e(change.length?change.join(' · '):d?.change||'按当前目标执行通用检查')+'</p>'+(d?'<small>适用判断：'+e(d.reason)+'</small>':'')+'</li><li><span>实际结果</span><p class="case-result">'+e(outcome)+'</p>'+(measured?'<small>个人经验新增 '+measured.addedPaths+' 条检查，已执行 '+measured.executedPersonalPaths+' 条。数量不代表收益。</small>':'')+'</li></ol><div class="case-bottom"><span>用户节省：尚未测得</span><a href="'+(ready?'/report':'#task')+'">'+(ready?'打开证据报告':'查看待执行计划')+' <span aria-hidden="true">↗</span></a></div>';
}

export const showcaseCSS=`
body:not([data-demo]){background:#f5f7fa;color:#192e48}
body:not([data-demo]) main{max-width:1280px;padding:0 48px 40px}
body:not([data-demo]) ::selection{background:#dbe7f5;color:#132d4c}
html{scroll-padding-top:24px}
.product-bar{display:flex;align-items:center;justify-content:space-between;gap:24px;min-height:88px;border-bottom:1px solid #cbd5df}
.product-brand{display:flex;align-items:center;gap:12px;text-decoration:none;font-size:21px;letter-spacing:-.02em}.product-brand svg{width:34px;height:34px}
.product-bar nav{display:flex;gap:30px}.product-bar nav a{font-size:14px;text-decoration:none;color:#4e6072;min-height:44px;display:inline-flex;align-items:center}.product-bar nav a:hover{color:#142f4e;text-decoration:underline}
.local-indicator{font-size:12px;color:#45634e;white-space:nowrap;display:flex;align-items:center;gap:8px}.local-indicator:before{content:'';width:6px;height:6px;background:#45634e;border-radius:50%}
header.showcase{display:grid;grid-template-columns:1fr 1.13fr;align-items:center;gap:60px;padding:52px 0 36px;border:0}
.showcase h1{font-size:clamp(32px,3.1vw,46px);font-weight:650;line-height:1.4;letter-spacing:-.035em;margin:0 0 22px;text-wrap:balance}
.showcase-lead{max-width:30em;font-size:17px;line-height:1.9;color:#4e6072;margin:0 0 28px}
.showcase-actions{display:flex;align-items:center;flex-wrap:wrap;gap:22px;font-size:14px}.action-link{display:inline-flex;align-items:center;justify-content:space-between;gap:24px;background:#1e3a5f;color:#fff;padding:13px 20px;border-radius:6px;text-decoration:none;min-height:48px}.action-link:hover{background:#132940;color:white}
.showcase-status{font-size:12px;color:#4e6072;margin-top:20px}.showcase-case{background:white;border:1px solid #cbd5df;border-radius:12px;padding:24px 28px}
.case-heading{display:flex;justify-content:space-between;align-items:center;gap:14px}.case-heading h2,.showcase-case>h2{font-size:20px;margin:0}.case-state{font-size:12px;color:#45634e;white-space:nowrap}.case-intro{font-size:13px;color:#4e6072;margin:9px 0 20px}
.case-flow{padding:0;list-style:none;margin:0;counter-reset:case-step}.case-flow li{position:relative;padding:0 0 18px 31px;margin-bottom:16px;border-bottom:1px solid #e3e8ee;counter-increment:case-step}.case-flow li:before{content:counter(case-step);position:absolute;left:0;top:0;font-size:12px;color:#4e6072;font-variant-numeric:tabular-nums}.case-flow li:last-child{margin-bottom:0}.case-flow li>span{display:block;font-size:12px;font-weight:600;color:#4e6072;margin-bottom:5px}.case-flow p,.case-flow blockquote{font-size:14px;line-height:1.8;margin:0;padding:0;background:none;border:0}.case-flow small{display:block;color:#4e6072;font-size:11px;margin-top:5px;line-height:1.7}.case-result{font-weight:600}.case-bottom{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px;padding-top:16px;font-size:12px}.case-bottom>span,.case-note{color:#4e6072}.case-note{font-size:12px}
.showcase-principle{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;border-top:1px solid #cbd5df;border-bottom:1px solid #cbd5df;padding:17px 0;font-size:13px}.showcase-principle span{color:#4e6072}
body:not([data-demo]) section{border-radius:10px;padding:28px 32px;margin:28px 0;box-shadow:none}body:not([data-demo]) #intake{max-width:960px;margin:32px auto}body:not([data-demo]) #intake h2{font-size:24px}body:not([data-demo]) #prepare{display:grid;grid-template-columns:1fr}body:not([data-demo]) #prepare>label{margin-top:20px}body:not([data-demo]) .gap{border:1px solid #e0c99f;border-radius:6px;background:#fffaf0}body:not([data-demo]) #message:empty{display:none}body:not([data-demo]) #user-guide{font-size:14px;margin-top:10px}body:not([data-demo]) #user-guide>summary{font-size:13px;color:#4e6072}body:not([data-demo]) #automatic-summary{padding:20px 24px;background:#f1f5fa;border-radius:8px;margin:22px 0}body:not([data-demo]) #automatic-summary h3{margin:0 0 10px}body:not([data-demo]) .check p{line-height:1.7}body:not([data-demo]) #execution>.buttons{padding:16px 0}body:not([data-demo]) #help-evaluation{margin-top:32px}body:not([data-demo]) #opinion{border-top:1px solid #cbd5df;margin-top:24px;padding-top:12px}
@media(max-width:960px){body:not([data-demo]) main{padding:0 28px 32px}header.showcase{gap:28px;grid-template-columns:1fr 1.1fr}.product-bar nav{gap:16px}.local-indicator{display:none}.showcase-case{padding:22px}}
@media(max-width:700px){body:not([data-demo]) main{padding:0 18px 28px}.product-bar{flex-wrap:wrap;gap:4px;padding:18px 0 8px}.product-bar nav{width:100%;justify-content:space-between;gap:10px}.product-brand{font-size:19px}.product-bar nav a{font-size:12px}header.showcase{grid-template-columns:1fr;padding:30px 0 24px;gap:22px}.showcase h1{font-size:34px;margin-bottom:14px}.showcase-lead{font-size:15px;margin-bottom:22px}.showcase-actions{gap:16px;font-size:13px}.showcase-case{padding:20px}.showcase-principle{font-size:12px}.showcase-principle strong{font-weight:500}body:not([data-demo]) section{padding:22px 18px}body:not([data-demo]) #automatic-summary{padding:16px}body:not([data-demo]) #report-pdf{display:inline-block;margin:12px 0}.case-heading{align-items:start}.case-heading h2{font-size:18px}.case-flow li{padding-left:25px}}
@media(prefers-reduced-motion:no-preference){.showcase-intro{animation:showcase-enter .35s ease-out}@keyframes showcase-enter{from{opacity:.65;transform:translateY(5px)}to{opacity:1;transform:none}}}
`;
